#!/bin/bash -e

function add_hashicorp_apt_repository {
  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
  sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

  # sudo apt-get update

  # sudo apt-cache policy consul
  # sudo apt-get install consul=1.8.3
  # sudo apt-get install -y consul

}

