#!/bin/bash -e

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 656408E390CFB1F5
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb.list

sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    mongodb-org-shell \
    mongodb-org-tools \
    mongodb-org-mongos \
    redis-tools

[[ "$(lsb_release -cs)" == "xenial" ]] && apt-get install -y --no-install-recommends libcurl3

