#!/bin/bash -e

sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends redis-server

sudo sed -i -e 's/bind 127.0.0.1/bind 0.0.0.0/' /etc/redis/redis.conf &&
    sudo service redis restart


