#!/bin/bash -e

echo "===== show-info ===== start"

echo "---------------------------------------------------"
echo ""

echo "dollar-at" "$@"

echo ""
echo "---------------------------------------------------"
echo ""

echo "1: |$1|"
echo "2: |$2|"
echo "3: |$3|"
echo "4: |$4|"
echo "5: |$5|"
echo "6: |$6|"
echo "7: |$7|"

echo ""
echo "---------------------------------------------------"
echo ""

echo "cloud-init /run/cloud-init"
ls -l /run/cloud-init

echo "cloud-init /var/lib/cloud"
ls -l /var/lib/cloud

echo "cloud-init /run/cloud-init/instance-data.json"
if [ -f /run/cloud-init/instance-data.json ]; then
  cat /run/cloud-init/instance-data.json
fi

echo "cloud-init /run/cloud-init/instance-data-sensitive.json"
if [ -f /run/cloud-init/instance-data-sensitive.json ]; then
  cat /run/cloud-init/instance-data-sensitive.json
fi

echo "cloud-init /var/lib/cloud/instance/user-data.txt"
if [ -f /var/lib/cloud/instance/user-data.txt ]; then
  cat /var/lib/cloud/instance/user-data.txt
fi

echo "cloud-init /var/lib/cloud/instance/vendor-data.txt"
if [ -f /var/lib/cloud/instance/vendor-data.txt ]; then
  cat /var/lib/cloud/instance/vendor-data.txt
fi

echo ""
echo "---------------------------------------------------"
echo ""

echo "ENV"
env | sort

echo ""
echo "---------------------------------------------------"
echo ""

echo "PATH"
echo "$PATH" | tr ':' '\n'

echo "===== show-info ===== end"
