#!/bin/bash -e

# ---------------------------------------------------------------------------------------------------------------------

# If we already have it, we done
hash vimcat 2> /dev/null && exit 0

# We need build tools
if ! hash make 2> /dev/null; then
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential
fi

# pandoc and doctoc
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends pandoc
if hash npm; then
  sudo npm install --global doctoc
fi


# clone; make install
mkdir -p /tmp/zz_packages/vim8 && cd $_
git clone git://github.com/rkitover/vimpager
cd vimpager
sudo make install-deb

# Clean up
cd /tmp/zz_packages
test -d vim8 && rm -rf vim8
# *********************************************************************************************************************

