#!/bin/bash -e


# ---------------------------------------------------------------------------------------------------------------------
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
sudo add-apt-repository -y ppa:rmescandon/yq
sudo apt update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends yq

# *********************************************************************************************************************

