#!/bin/bash -e

echo "ENV:"
env | sort

scripts_dir="$(dirname $0)"

echo "============================================================================================="
echo "pwd: $(pwd); scripts_dir: $scripts_dir"
echo $*


