#!/bin/bash -e

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

sudo apt-add-repository -y ppa:maarten-fonville/android-build-tools
sudo apt-get update

sudo apt-get install -y android-build-tools-installer

