#!/bin/bash -e

# readlink_f() { which greadlink > /dev/null && greadlink -f $1 || readlink -f $1; }
# script_dir="$( cd "$(dirname "$( readlink_f "${BASH_SOURCE[0]}" )" )" && pwd )"

if which aws > /dev/null; then
  sudo -H pip uninstall -y awscli
fi


cd
mkdir -p zz_packages
cd zz_packages

curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install






