#!/bin/bash -e

# readlink_f() { which greadlink > /dev/null && greadlink -f $1 || readlink -f $1; }
# script_dir="$( cd "$(dirname "$( readlink_f "${BASH_SOURCE[0]}" )" )" && pwd )"

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

curl -sSL 'https://apt.corretto.aws/corretto.key' | sudo apt-key add -
sudo add-apt-repository 'deb https://apt.corretto.aws stable main'
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y java-1.8.0-amazon-corretto-jdk

# TODO: Setup JAVA_HOME, et. al.
