#!/bin/bash -e

script_dir="$( cd "$(dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd )"

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

ssh-keygen -F github.com || ssh-keyscan github.com >> "${HOME}/.ssh/known_hosts"
sudo apt-get install -y git


