#!/bin/bash -e

echo Installing Node.js v12

# Get the key
curl -L https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -

# Cloud-Config
sudo echo "deb https://deb.nodesource.com/node_12.x ${OS_CODENAME} main" > /etc/apt/sources.list.d

sudo apt-get update
sudo apt-get install -y nodejs

# vim: ft=bash:
