#!/bin/bash -e


readlink_f() { which greadlink > /dev/null && greadlink -f $1 || readlink -f $1; }
script_dir="$( cd "$(dirname "$( readlink_f "${BASH_SOURCE[0]}" )" )" && pwd )"

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

# ---------------------------------------------------------------------------------------------------------------------
# Source utils
. "${script_dir}/common/hashicorp"

add_hashicorp_apt_repository

sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends vault

exit 0
# *********************************************************************************************************************




URL="https://releases.hashicorp.com/vault/1.4.2/vault_1.4.2_linux_amd64.zip"
PATHNAME="/usr/bin/vault"

[[ -f ${PATHNAME} ]] && die "already exists, stopping."

cd
mkdir -p zz_packages && cd $_

curl -sSL "$URL" -o vault.zip
unzip vault.zip

sudo mv vault "${PATHNAME}"
sudo chown root:root "${PATHNAME}"
sudo chmod +x "${PATHNAME}"

cd
rm -f zz_packages/vault.zip




