#!/bin/bash -e

readlink_f() { which greadlink > /dev/null && greadlink -f $1 || readlink -f $1; }
script_dir="$( cd "$(dirname "$( readlink_f "${BASH_SOURCE[0]}" )" )" && pwd )"

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }


# echo Installing vim8

# ---------------------------------------------------------------------------------------------------------------------
sudo add-apt-repository -y ppa:jonathonf/vim
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends vim

# ------------------------------------------------------------------------------------------------
# vimrc
cat << 'EOF' >> "${HOME}/.vimrc"
:let mapleader = ","
:set nocompatible

:set hidden
:set showcmd
:set nu
:syntax on
:set ruler
:set clipboard=unnamed
":set autoread
highlight StatusLine ctermfg=blue ctermbg=yellow

filetype plugin indent on

" Whitespace
:set nowrap
:set tabstop=2
:set shiftwidth=2
:set expandtab
:set smartindent
:set backspace=indent,eol,start

" Searching
:set hlsearch
:set incsearch
:set ignorecase
:set smartcase

" Next / Previous tab
:map <F7> :tabp<CR>
:map <F8> :tabn<CR>

" Open file from the same dir
:map <Leader>e :e <C-R>=expand("%:p:h") . '/'<CR>

" Clear search
nmap <silent> ,. :nohlsearch<CR>

:color desert

EOF

chownmod ubuntu:ubuntu 0644 "${HOME}/.vimrc"
# *********************************************************************************************************************


# vim: ft=bash:
