#!/bin/bash -e

echo Installing vimbcs

pathogen()
{
  git_user="$1"
  module="$2"

  # (***)
  if ! [[ -d ~/.vim/bundle/${module} ]]; then
    (cd ~/.vim/bundle && git clone --depth=1 https://github.com/${git_user}/${module}.git)
  fi
}

scripts_dir="$(dirname $0)"

# VIM setup
mkdir -p ~/.vim/autoload ~/.vim/bundle

test -f ~/.vim/autoload/pathogen.vim || curl -SLso ~/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim



pathogen vim-ctrlspace vim-ctrlspace
pathogen scrooloose syntastic
pathogen mxw vim-jsx
pathogen pangloss vim-javascript
pathogen rust-lang rust.vim
pathogen kballard vim-swift
pathogen tpope vim-markdown
pathogen jneen ragel.vim
pathogen chr4 nginx.vim

# vim-javascript and vim-jsx do horrible indentation
# (***)
if [[ -d ~/.vim/bundle/vim-javascript/indent ]]; then
  rm -rf ~/.vim/bundle/vim-javascript/indent
  rm -f ~/.vim/bundle/vim-jsx/after/indent/jsx.vim
fi


cp ${scripts_dir}/../files/vimbcs/vimrc ${HOME}/.vimrc


# vim: ft=bash:
